sudo: required

language: minimal

services: docker

branches:
    only:
        - master

script:
    # conventional image name, but no intention to push it so far
    - docker build -t liberoadmin/patterns-core .

after_success:
    - docker run --name patterns-core liberoadmin/patterns-core node_modules/.bin/gulp exportPatterns
    # TODO: empty out committed export/ folder
    - docker cp patterns-core:/patterns-core/export/. export/
