sudo: required

language: minimal

services: docker

branches:
    only:
        - master

script:
    # conventional image name, but no intention to push it so far
    - docker build -t liberoadmin/patterns-core .
