version: '3'

services:
    patterns:
        build:
            context: .
            dockerfile: Dockerfile.patterns
        image: liberoadmin/patterns-core_patterns
    composer:
        build:
            context: .
            dockerfile: Dockerfile.composer
        image: liberoadmin/patterns-core_composer
    ui-builder:
        build:
            context: .
            dockerfile: Dockerfile.ui-builder
        image: liberoadmin/patterns-core_ui-builder
        ports:
            - "8889:8080"
        depends_on:
            - patterns
            - composer

