version: '3'

services:
    patterns:
        build:
            context: .
            dockerfile: Dockerfile.patterns
        image: liberoadmin/patterns-core_patterns
    composer:
        build:
            context: .
            dockerfile: Dockerfile.composer
        image: liberoadmin/patterns-core_composer

