version: '3.4'

services:
  ui:
    build:
      context: .
      target: ui
      args:
        revision: ${IMAGE_REVISION:-master}
    image: libero/pattern-library:${IMAGE_TAG:-master}
    ports:
      - 8889:80
