version: '3'

services:
    patterns:
        build:
            context: .
            dockerfile: Dockerfile.patterns
        image: liberoadmin/patterns-core_patterns
    composer:
        build:
            context: .
            dockerfile: Dockerfile.composer
        image: liberoadmin/patterns-core_composer
        command: /bin/sh
    ui-builder:
        build:
            context: .
            dockerfile: Dockerfile.ui-builder
        image: liberoadmin/patterns-core_ui-builder
        depends_on:
            - patterns
            - composer
    ui-viewer:
        # TODO: probably use its own Dockerfile and image
        image: liberoadmin/patterns-core_ui-builder
        command: php -S 0.0.0.0:8080 -t /ui-builder/public /ui-builder/core/server/router.php
        ports:
            - "8889:8080"
        depends_on:
            - ui-builder

