version: '3'

services:
    patterns:
        command: bash -c "node libero-config/bin/distributeConfig.js && npx gulp watch"
        volumes:
            - ./source:/patterns-core/source
    ui-builder:
        command: php ./core/console --watch
        volumes:
            - ./source:/ui-builder/source
            - public:/ui-builder/public
    ui-viewer:
        volumes:
            - public:/ui-builder/public

volumes:
    public:
