version: '3.4'

services:
  watch-gulp:
    build:
      context: .
      target: gulp
    command: bash -c "npx gulp build --environment=development --lint=${LINT} && npx gulp watch --environment=development --lint=${LINT}"
    restart: on-failure
    volumes:
      - ./build:/app/build
      - ./source:/app/source
      - ./test:/app/test
  watch-build:
    build:
      context: .
      target: build
    command: core/watch
    restart: on-failure
    volumes:
      - ./build/public:/app/build/public
      - ./build/source:/app/build/source:ro
    depends_on:
      - watch-gulp
  ui:
    build:
      context: .
      target: gulp
    command: npx gulp server
    ports:
      - 8889:80
      - 3000:3000
    volumes:
      - ./build/public:/app/build/public:ro
    depends_on:
      - watch-build
