blg:
  space:
    extra-small-in-px: 12
    small-in-px: !expression blg.space.extra-small-in-px * 2
    smallish-in-px: !expression blg.space.small-in-px * 1.5
    medium-in-px: !expression blg.space.small-in-px * 2
    large-in-px: !expression blg.space.small-in-px * 3
    extra-large-in-px: !expression blg.space.small-in-px * 5

breakpoints:
  site:
    x-small: 320
    small: 480
    medium: 730
    wide: 900
    x-wide: 1200

libero:
  color:
    primary:
      light: '#b3e5fc'
      normal: '#0288d1'
      dark: '#0277bd'
    text:
      normal: '#212121'
      reverse: '#fff'
      secondary: '#888'
      secondary-reverse: '#9e9e9e'
      placeholder: '#bdbdbd'
      dividers: '#e0e0e0'
      dividers-reverse: '#616161'
      background: '#fff'
      background-hue: '#f5f5f5'
      ui-code: '#f7f7f7'
      ui-background--reverse: '#212121'
      ui-background-hue--reverse: '#333'
    information: '#0288d1'
    success: '#629f43'
    success-dark: '#569037'
    attention: '#cf0c4e'
