#!/usr/bin/env php
<?php

use Lurker\ResourceWatcher;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Process\Process;

require_once __DIR__ . '/../vendor/autoload.php';

(new Application())
    ->register('watch')
    ->setCode(function (InputInterface $input, OutputInterface $output): void {
        $watcher = new ResourceWatcher;
        $watcher->track('source', __DIR__ . '/../source');

        $process = new Process(['core/console', '--generate']);
        $process->setWorkingDirectory(__DIR__ . '/..');

        $watcher->addListener('source', function () use ($output, $process) : void {
            $process->run(function ($type, $buffer) use ($output) : void {
                $output->write($buffer);
            });
        });

        $watcher->start();
    })
    ->getApplication()
    ->setDefaultCommand('watch', true)
    ->run();
